; memtest.s
;
; Boot ROM memory test for the be6502 build (W65C816S).
;
; Exercises RAM banks $01-$07 (the AS6C4008, per README.md) by writing and
; reading back a pseudo-random byte at a pseudo-random offset within each
; bank, using 65C816 direct-page indirect long addressing ("[dp]") so a
; full 24-bit bank:offset address can be reached without leaving emulation
; mode. Address offsets are generated by a maximal-length 16-bit Galois
; LFSR (taps 16/14/13/11, period 65535), run for one full period per bank
; -- effectively exhaustive coverage of each 64K bank.
;
; On completion, $01 is written to VIA port B if every comparison
; succeeded, or $02 as soon as the first mismatch is found.
;
; Assemble with vasm (6502 backend, oldstyle syntax):
;   vasm6502_oldstyle -816 -Fbin -dotdir -o memtest.bin memtest.s

.as                             ; 8-bit accumulator (emulation-mode reset state)
.xs                             ; 8-bit index registers (emulation-mode reset state)

VIA_ORB     equ $6000            ; VIA port B output register
VIA_DDRB    equ $6002            ; VIA port B data direction register

STATUS_OK   equ $01
STATUS_FAIL equ $02

BANK_FIRST  equ $01
BANK_LAST   equ $07
BANK_LIMIT  equ BANK_LAST+1

; Direct-page (zero page) working storage.
ptr_lo      equ $00              ; 24-bit pointer for [dp] addressing:
ptr_hi      equ $01              ;   ptr_lo/ptr_hi/ptr_bank, low to high
ptr_bank    equ $02
rng_lo      equ $03              ; 16-bit LFSR state; also supplies the
rng_hi      equ $04              ;   low/high bytes of the test offset
count_lo    equ $05              ; tests remaining in the current bank
count_hi    equ $06
data_byte   equ $07              ; pseudo-random pattern under test

    org $8000

reset:
    sei
    cld
    ldx     #$ff
    txs

    ; VIA port B is all outputs so the status byte can be written.
    lda     #$ff
    sta     VIA_DDRB

    ; Seed the LFSR. Must be non-zero or it will never advance.
    lda     #$ac
    sta     rng_hi
    lda     #$e1
    sta     rng_lo

    lda     #BANK_FIRST
    sta     ptr_bank

bank_loop:
    ; One full LFSR period ($FFFF tests) per bank.
    lda     #$ff
    sta     count_lo
    sta     count_hi

test_loop:
    jsr     lfsr_advance

    lda     rng_lo
    sta     ptr_lo
    lda     rng_hi
    sta     ptr_hi

    ; Test pattern: a simple mix of the address bytes, inverted, so it
    ; never trivially matches the address it is stored at.
    lda     rng_lo
    eor     rng_hi
    eor     #$ff
    sta     data_byte

    lda     data_byte
    sta     [ptr_lo]

    lda     [ptr_lo]
    cmp     data_byte
    bne     fail

    lda     count_lo
    bne     count_dec
    dec     count_hi
count_dec:
    dec     count_lo
    lda     count_lo
    ora     count_hi
    bne     test_loop

    inc     ptr_bank
    lda     ptr_bank
    cmp     #BANK_LIMIT
    bne     bank_loop

success:
    lda     #STATUS_OK
    sta     VIA_ORB
    jmp     halt

fail:
    lda     #STATUS_FAIL
    sta     VIA_ORB

halt:
    jmp     halt

; 16-bit Galois LFSR (poly $B400, taps 16/14/13/11) over rng_hi:rng_lo.
lfsr_advance:
    lsr     rng_hi
    ror     rng_lo
    bcc     lfsr_done
    lda     rng_hi
    eor     #$b4
    sta     rng_hi
lfsr_done:
    rts

irq_nmi_stub:
    rti

    org $ffe4
    dc.w irq_nmi_stub      ; $FFE4 COP    (native)
    dc.w irq_nmi_stub      ; $FFE6 BRK    (native)
    dc.w irq_nmi_stub      ; $FFE8 ABORTB (native)
    dc.w irq_nmi_stub      ; $FFEA NMIB   (native)
    dc.w $0000             ; $FFEC reserved
    dc.w irq_nmi_stub      ; $FFEE IRQB   (native)
    dc.w $0000             ; $FFF0 reserved
    dc.w $0000             ; $FFF2 reserved
    dc.w irq_nmi_stub      ; $FFF4 COP    (emulation)
    dc.w $0000             ; $FFF6 reserved
    dc.w irq_nmi_stub      ; $FFF8 ABORTB (emulation)
    dc.w irq_nmi_stub      ; $FFFA NMIB   (emulation)
    dc.w reset             ; $FFFC RESET
    dc.w irq_nmi_stub      ; $FFFE IRQB/BRK (emulation)
